version: "3.9"

services:
  backend:
    build:
      context: ./src
      dockerfile: ./backend.Dockerfile
  postgres:
    image: postgres:13.7-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
